# Stack Docker Compose pour le Développement Local

services:
  mongo:
    image: mongo:4.4
    container_name: luminaview-mongo
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db
    networks:
      - luminaview-local-network

  backend:
    build: ./backend
    container_name: luminaview-backend
    restart: unless-stopped
    ports:
      - "7099:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./data/uploads:/app/uploads
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/luminaview_core
      - JWT_SECRET=changeThisSecretLuminaView123!
      - PORT=3000
      - FRONTEND_URL=http://localhost:7080
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_FROM=test@helioscope.fr
    networks:
      - luminaview-local-network

  manager:
    build:
      context: .
      dockerfile: ./apps/manager/Dockerfile
    container_name: luminaview-manager
    restart: unless-stopped
    ports:
      - "7080:80"
    depends_on:
      - backend
    networks:
      - luminaview-local-network

  blog:
    build:
      context: .
      dockerfile: ./apps/blog/Dockerfile
    container_name: luminaview-blog
    restart: unless-stopped
    ports:
      - "7081:80"
    depends_on:
      - backend
    networks:
      - luminaview-local-network

  portfolio:
    build:
      context: .
      dockerfile: ./apps/portfolio/Dockerfile
    container_name: luminaview-portfolio
    restart: unless-stopped
    ports:
      - "7090:80"
    depends_on:
      - backend
    networks:
      - luminaview-local-network

  chambrenoire:
    build:
      context: .
      dockerfile: ./apps/chambrenoire/Dockerfile
    container_name: luminaview-chambrenoire
    restart: unless-stopped
    ports:
      - "7082:80"
    depends_on:
      - backend
    networks:
      - luminaview-local-network

  grimoire:
    build:
      context: .
      dockerfile: ./apps/grimoire/Dockerfile
    container_name: luminaview-grimoire
    restart: unless-stopped
    ports:
      - "7091:80"
    depends_on:
      - backend
    networks:
      - luminaview-local-network

  # --- MAILHOG ---
  mailhog:
    image: mailhog/mailhog
    container_name: luminaview-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - luminaview-local-network

networks:
  luminaview-local-network:
    driver: bridge
