server {
    listen 80 default_server;
    server_name _;

    client_max_body_size 300M;

    # 1. LE BLOG PUBLIC (URL: /blog)
#    location /blog {
#        # On envoie au Frontend du Blog
#        proxy_pass http://blog-frontend:80;
#       proxy_http_version 1.1;
#        proxy_set_header Host $host;
#        proxy_set_header X-Real-IP $remote_addr;
#        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#        proxy_set_header X-Forwarded-Proto $scheme;
#    }

    # (Supprimé : location /api/blog/ car ça remplaçait mal l'URL et cassait les requêtes blog)

    # --- AJOUTER CECI ---
   # Redirige l'affichage des articles vers le Frontend du Blog
   location /post/ {
       proxy_pass http://blog;
       proxy_http_version 1.1;
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
   }
   # --------------------


    # 3. API PRINCIPALE
    location /api {
        proxy_pass http://backend:3000;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

    }

    # IMAGES
    location /uploads {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # --- NOUVEAU BLOC AJOUTE ---
    # 5. FICHIERS STATIQUES (JS, CSS)
    # On essaie d'abord de les servir depuis l'appli principale, sinon on redirige vers le blog
    location /static/ {
        root /usr/share/nginx/html;
        try_files $uri @blog_fallback;
    }

    location @blog_fallback {
        proxy_pass http://blog;
        proxy_set_header Host $host;
    }
    # ----------------------------

    # 5. REACT APP (Dashboard, Login, ET Manager)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
