services:
  mongo:
    image: mongo:4.4
    container_name: luminaview-mongo
    volumes:
      - ../data/mongo:/data/db
    networks:
      - luminaview-network

  backend:
    build: ./backend
    container_name: luminaview-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ../data/uploads:/app/uploads
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/luminaview_core
      - JWT_SECRET=changeThisSecretLuminaView123!
      - PORT=3000
    networks:
      - luminaview-network

  manager:
    build: ./apps/manager
    container_name: luminaview-manager
    ports:
      - "7080:80"
    depends_on:
      - backend
    networks:
      - luminaview-network

  blog:
    build: ./apps/blog
    container_name: luminaview-blog
    ports:
      - "7081:80"
    depends_on:
      - backend
    networks:
      - luminaview-network

  portfolio:
    build: ./apps/portfolio
    container_name: luminaview-portfolio
    ports:
      - "7090:80"
    depends_on:
      - backend
    networks:
      - luminaview-network

  chambrenoire:
    build: ./apps/chambrenoire
    container_name: luminaview-chambrenoire
    ports:
      - "7082:80"
    depends_on:
      - backend
    networks:
      - luminaview-network

networks:
  luminaview-network:
    driver: bridge
