server {
    listen 80;
    server_name _;

    # 1. REDIRECTION IMAGES -> VERS L'APP PRINCIPALE
    location /uploads/ {
        proxy_pass http://backend:3000/uploads/;
        proxy_set_header Host $host;
    }

    # 2. REDIRECTION API -> BLOG BACKEND
    location /api/blog {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. REACT APP
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
